language: cpp

sudo: required

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - libxml2-dev
      - libxslt1-dev

install:
  - sudo pip install --upgrade pip wheel

script:
  - python -V
  - gcc -v
  - ls -al
  - mkdir wheels
  - pip install wheel
  - pip wheel pyahocorasick --wheel-dir=wheels
  - pip wheel intbitset --wheel-dir=wheels
  - pip wheel bitarray --wheel-dir=wheels
  - pip wheel lxml==3.6.4 --wheel-dir=wheels
  - pip wheel lxml==3.6.0 --wheel-dir=wheels
  - pip wheel lxml==4.1.1 --wheel-dir=wheels
  - pip wheel tinyarray --wheel-dir=wheels
  - pip wheel simplejson --wheel-dir=wheels
  - pip wheel billiard --wheel-dir=wheels
  - pip wheel psutil --wheel-dir=wheels
  - pip wheel pycryptodome --wheel-dir=wheels
  
  - ls -al
  - "pip download -d wheels --no-binary :all: pyahocorasick"
  - "pip download -d wheels --no-binary :all: intbitset"
  - "pip download -d wheels --no-binary :all: bitarray"
  - "pip download -d wheels --no-binary :all: lxml==3.6.4"
  - "pip download -d wheels --no-binary :all: lxml==3.6.0"
  - "pip download -d wheels --no-binary :all: lxml==4.1.1"
  - "pip download -d wheels --no-binary :all: tinyarray"
  - "pip download -d wheels --no-binary :all: simplejson"
  - "pip download -d wheels --no-binary :all: billiard"
  - "pip download -d wheels --no-binary :all: psutil"
  - "pip download -d wheels --no-binary :all: pycryptodome"
  - ls -al wheels

deploy:
  provider: bintray
  file: bintray_travis.json
  user: pombreda
  key:
    secure: l8uNfriu2L+rHRRBsR8R6pGHFt+r1Rymfk+1pOKdJTR8NjgBAYEAxPU6IPr+drH1WheXGVFoWttWTcplvo8Xmc+skUMXKUnjNCgrRE0rYKqjdHmEBMKUAjAfZ3hq48ayjRm3FvAjPwcWbTD0siBjK1qm4SD7TBEEC28XuJhT1oE=
