language: python

python:
  - '2.7'

branches:
  only:
  - master

env:
  global:
    # OAuth token for Travis to commit back to Github
    - secure: "Y+sm5V6m1iAeGCVNe/5clvwYrks8wAlUp0JhOV3T9ditaLpcQEEPU09PT1tojeFTq1mTx7atnMhQRolh8XSt3h9t2WzgqJ7ZbW7cbVqMSMJSzf0UGKcq8g0oCei2v9aNwiYIllqndbPlatO/vebpsejw2xrM7SQ8K/BgzwQLtBw="

install:
  # Setup extra packages as needed
  # - sudo apt-get update -qq
  # - sudo apt-get install -y libxml2-dev
  # - sudo apt-get install -y libxslt-dev
  # Clone and branch
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_NAME}"
  - git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git ~/thirdparty
  - cd ~/thirdparty
  - git checkout -b packages origin/packages
  # Merge latest requirements from master
  - git merge -m "Merging latest master requirements in packages" ${TRAVIS_COMMIT}

script:
  # deactivate from Travis venv
  - deactivate
  # Install our pip, setuptools in a virtualenv
  - cd ~/thirdparty
  - python2.7 dist/virtualenv.py --never-download --extra-search-dir=dist/ .
  - source bin/activate
  # download if needed or reuse known requirements
  - pip install --use-wheel --find-links=dist/ --download=dist/ -r requirements.txt
  # install proper
  - pip install --no-index --no-allow-external --use-wheel --find-links=dist/  -r requirements.txt
  # wheel the downloads
  - pip wheel --no-index --no-allow-external --wheel-dir dist/ --find-links=dist/ -r requirements.txt 
  # regenerate index
  # - TBD

after_success:
  # commit new downlaods and built wheels
  - cd ~/thirdparty
  - git add -u .
  - git status
  - git commit -m "New packages built via Travis for master commit:${TRAVIS_COMMIT}"
  - git push -all https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
 