language: python
# The Travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable. 
python: 3.5
dist: trusty
services: docker

os:
    - linux
    - osx

env:
    global:
        - PLAT=x86_64
        - MB_PYTHON_OSX_VER=10.9
    matrix:
        - UNICODE_WIDTH=16
        - UNICODE_WIDTH=32
        - PROJECT_SPEC: pyahocorasick
        - PROJECT_SPEC: lxml
        - PROJECT_SPEC: tinyarray
        - PROJECT_SPEC: simplejson
        - PROJECT_SPEC: billiard
        - PROJECT_SPEC: psutil
        - PROJECT_SPEC: intbitset
        - PROJECT_SPEC: bitarray
        - PROJECT_SPEC: pycryptodome
        - PROJECT_SPEC: rdflib
        - PROJECT_SPEC: url==0.1.6
        - PROJECT_SPEC: scandir
        - PROJECT_SPEC: pyyaml==3.12 
        - PROJECT_SPEC: pyyaml 
        - PROJECT_SPEC: cdifflib   
        - PROJECT_SPEC: edlib 
        - PROJECT_SPEC: hyperscan  
        - PROJECT_SPEC: pyroaring     
        - MB_PYTHON_VERSION=2.7
        - MB_PYTHON_VERSION=3.6

matrix:
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5


before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - ls -al ${TRAVIS_BUILD_DIR}/wheelhouse/

script:
    - build_index_wheel $PROJECT_SPEC 
    - ls -al ${TRAVIS_BUILD_DIR}/wheelhouse/

deploy:
  provider: bintray
  skip_cleanup: true
  file: bintray_travis.json
  user: pombreda
  key:
    secure: l8uNfriu2L+rHRRBsR8R6pGHFt+r1Rymfk+1pOKdJTR8NjgBAYEAxPU6IPr+drH1WheXGVFoWttWTcplvo8Xmc+skUMXKUnjNCgrRE0rYKqjdHmEBMKUAjAfZ3hq48ayjRm3FvAjPwcWbTD0siBjK1qm4SD7TBEEC28XuJhT1oE=

