language: cpp

#os:
  #- linux
  # - osx

branches:
  only:
  - master

env:
  global:
    # OAuth token for Travis to commit back to Github
    - secure: "Y+sm5V6m1iAeGCVNe/5clvwYrks8wAlUp0JhOV3T9ditaLpcQEEPU09PT1tojeFTq1mTx7atnMhQRolh8XSt3h9t2WzgqJ7ZbW7cbVqMSMJSzf0UGKcq8g0oCei2v9aNwiYIllqndbPlatO/vebpsejw2xrM7SQ8K/BgzwQLtBw="
    - cd ~/
    - HERE=$(pwd)
    - PYTON_VER=2.7
    - PYTHON_MINOR=2.7.8
    - export PYTHON_PATH=$HERE/python$PYTHON_VER
    - PYTHON_ARCHIVE=Python-$PYTHON_MINOR
    - PYTHON_DOWNLOAD=https://www.python.org/ftp/python/$PYTHON_MINOR/$PYTHON_ARCHIVE.tgz
    - export PYTON_EXE=python$PYTHON_VER
    - set | grep PY
install:
  - echo "installing Python"
  - mkdir -p $PYTHON_PATH
  - cd $PYTHON_PATH && curl --progress-bar --location "$PYTHON_DOWNLOAD" | tar -zx
  - cd $PYTHON_PATH/$PYTHON_ARCHIVE
  - ./configure --prefix $PYTHON_PATH >/dev/null 2>&1 
  - make >/dev/null 2>&1 
  - make install >/dev/null 2>&1
  - $PYTHON_PATH/bin/$PYTHON_EXE --version
  - echo "Done installing Python"

  # Setup extra packages as needed
  # use $TRAVIS_OS_NAME is linux or osx
  # - sudo apt-get update -qq
  # - sudo apt-get install -y libxml2-dev
  # - sudo apt-get install -y libxslt-dev
  # Clone and branch
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_NAME}"
  - git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git ~/thirdparty
  - cd ~/thirdparty
  - git checkout -b packages origin/packages
  # Merge latest requirements from master
  - git merge -m "Merging latest master requirements in packages" ${TRAVIS_COMMIT}
  - git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git packages

script:
  # Install our pip, setuptools in a virtualenv
  - cd ~/thirdparty
  - "$PYTHON_PATH/bin/$PYTHON_EXE" dist/virtualenv.py --never-download --extra-search-dir=dist/ .
  - source bin/activate
  # download if needed or reuse known requirements
  - pip install --use-wheel --find-links=dist/ --download=dist/ -r requirements.txt
  # install proper
  - pip install --no-index --no-allow-external --use-wheel --find-links=dist/  -r requirements.txt
  # wheel the downloads
  - pip wheel --no-index --no-allow-external --wheel-dir dist/ --find-links=dist/ -r requirements.txt 
  - find ~/thirdparty/dist
  # regenerate index
  # - TBD
  # commit new downlaods and built wheels
  - git status
  - git add -A --verbose dist
  - git status
  - git commit -m "New packages built via Travis for master commit:${TRAVIS_COMMIT}"
  - git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git packages
