language: python

python:
  - 2.7.13

sudo: required


# Travis does not offer OSX with arbitrary python versions (like 2.7.13 above)
# So, you can not simply have the following section in your build matrix:
# os:
#   - linux
#   - osx
# Instead, you have to include OSX entries into the build matrix manually.
# In particular, this means specifying the environment variables again.

# The following was adapted from here:
#   https://docs.travis-ci.com/user/multi-os/
# Set TEST_SUITE in `env:` so that the `script:` section below works
# Set `language: generic` to clear `language: python` from above
# Set `python:` (to empty) to clear it from the travis-ci web interface
# Set `osx_image: xcode7.3` to pin OSX and Python versions, see here:
#   https://docs.travis-ci.com/user/osx-ci-environment/

matrix:
  include:
    - os: osx
      language: generic
      python:
      osx_image: xcode7.3

#    - os: linux
#      language: python
#      python: 2.7.13


addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - libxml2-dev
      - libxslt1-dev

install:
  - python -V
  - sudo pip install --upgrade pip wheel

script:
  - python -V
  - gcc -v
  - ls -al
  - mkdir wheels
  - pip install wheel
  - pip wheel pyahocorasick --wheel-dir=wheels
  - pip wheel intbitset --wheel-dir=wheels
  - pip wheel bitarray --wheel-dir=wheels
  - pip wheel lxml --wheel-dir=wheels
  - pip wheel tinyarray --wheel-dir=wheels
  - pip wheel simplejson --wheel-dir=wheels
  - pip wheel billiard --wheel-dir=wheels
  - pip wheel psutil --wheel-dir=wheels
  - pip wheel pycryptodome --wheel-dir=wheels
  - pip wheel rdflib --wheel-dir=wheels
  - pip wheel url --wheel-dir=wheels
  
  
  - ls -al
  - "pip download -d wheels --no-binary :all: pyahocorasick"
  - "pip download -d wheels --no-binary :all: intbitset"
  - "pip download -d wheels --no-binary :all: bitarray"
  - "pip download -d wheels --no-binary :all: lxml
  - "pip download -d wheels --no-binary :all: tinyarray"
  - "pip download -d wheels --no-binary :all: simplejson"
  - "pip download -d wheels --no-binary :all: billiard"
  - "pip download -d wheels --no-binary :all: psutil"
  - "pip download -d wheels --no-binary :all: pycryptodome"
  - "pip download -d wheels --no-binary :all: rdflib"
  - "pip download -d wheels --no-binary :all: url"

  - ls -al wheels

deploy:
  provider: bintray
  skip_cleanup: true
  file: bintray_travis.json
  user: pombreda
  key:
    secure: l8uNfriu2L+rHRRBsR8R6pGHFt+r1Rymfk+1pOKdJTR8NjgBAYEAxPU6IPr+drH1WheXGVFoWttWTcplvo8Xmc+skUMXKUnjNCgrRE0rYKqjdHmEBMKUAjAfZ3hq48ayjRm3FvAjPwcWbTD0siBjK1qm4SD7TBEEC28XuJhT1oE=
