language: cpp

os: 
  - osx
  - linux 

install:
    - pip install --upgrade pip wheel

script:
    - python -V
    - gcc -v
    - ls -al
    - mdkdir wheels
    - cd pyahocorasick
    - pip wheel pyahocorasick intbitset bitarray --wheel-dir=wheels
    - ls -al
    - ls -al wheels