python:
  - '2.7'

branches:
  only:
  - master

env:
  global:
    # OAuth token for Travis to commit back to Github
    - secure: "Y+sm5V6m1iAeGCVNe/5clvwYrks8wAlUp0JhOV3T9ditaLpcQEEPU09PT1tojeFTq1mTx7atnMhQRolh8XSt3h9t2WzgqJ7ZbW7cbVqMSMJSzf0UGKcq8g0oCei2v9aNwiYIllqndbPlatO/vebpsejw2xrM7SQ8K/BgzwQLtBw="

before_install:
    - pwd
    - cp requirements.txt ${HOME}/requirements.txt
   
install:
  # Setup extra packages as needed
  # - sudo apt-get update -qq
  # - sudo apt-get install -y libxml2-dev
  # - sudo apt-get install -y libxslt-dev
  # Clone and branch
  - git clone --branch packages https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git ${HOME}/thirdparty
  # copy the latest master requirements and copy these to the branch
  - cp ${HOME}/requirements.txt ${HOME}/thirdparty/requirements.txt

script:
  # Install pip, setuptools in a virtualenv
  - cd ${HOME}/thirdparty
  - python2.7 dist/virtualenv.py --never-download --extra-search-dir=dist/ .
  - source bin/activate
  # download and install requirements
  - pip install --use-wheel --find-links=dist/ --download=dist/ -r requirements.txt
  # wheel'em
  - pip wheel --no-index --no-allow-external --use-wheel --wheel-dir dist --find-links=dist/ -r requirements.txt 
  # regenerate index
  # - TBD

after_success:
  # commit new wheels
  - cd ${HOME}/thirdparty
  - git add -f requirements.txt
  - git add -f dist/*
  - git status
  - git commit -m "New dist packages built via Travis build: ${TRAVIS_BUILD_NUMBER} for master commit:${TRAVIS_COMMIT}"
  # - git push --quiet https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git packages
  - git push origin ref/heads/packages
