language: cpp

os: 
  - osx
  - linux 

install:
    - pip install --upgrade pip wheel

script:
    - python -V
    - gcc -v
    - git clone https://github.com/WojciechMula/pyahocorasick.git
    - ls -al
    - cd pyahocorasick
    - pip wheel .
    - ls -al