install:
    - cmd: "C:\\Python27\\python.exe -m pip install --upgrade pip wheel"
build: off
test_script:
    - dir
    - mkdir wheels
    - cmd: "C:\\Python27\\python.exe -m pip wheel pyahocorasick intbitset bitarray --wheel-dir=wheels"
    - dir
    - dir wheels