
install:
    - cmd: "C:\\Python27\\\python.exe -m pip install --upgrade pip wheel"
    - cmd: "C:\\Python27-x64\\\python.exe -m pip install --upgrade pip wheel"

build: off

test_script:
    - dir
    - mkdir wheels
    - cmd: "C:\\Python27\\python.exe -m pip wheel pyahocorasick intbitset bitarray --wheel-dir=wheels"
    - cmd: "C:\\Python27-x64\\python.exe -m pip wheel pyahocorasick intbitset bitarray --wheel-dir=wheels"
    - dir
    - dir wheels

deploy:
    - provider: BinTray
      username: pombreda
      api_key:
        secure: vfOXPuSdGaUBQWCWhtXGWOKFoWulmg8dl3J8EP7RodmMN96VH8yeMQIHdU3f4+l/
      subject: pombreda
      repo: thirdparty
      package: thirdparty
      publish: true
      override: true
      artifact: "/wheels\\.*/"