environment:
  matrix:
    - PYTHON: "C:\\Python27"
      WHEEL: pyahocorasick
    - PYTHON: "C:\\Python27"
      WHEEL: lxml
    - PYTHON: "C:\\Python27"
      WHEEL: tinyarray
    - PYTHON: "C:\\Python27"
      WHEEL: simplejson
    - PYTHON: "C:\\Python27"
      WHEEL: billiard
    - PYTHON: "C:\\Python27"
      WHEEL: psutil
    - PYTHON: "C:\\Python27"
      WHEEL: intbitset
    - PYTHON: "C:\\Python27"
      WHEEL: bitarray
    - PYTHON: "C:\\Python27"
      WHEEL: pycryptodome
    - PYTHON: "C:\\Python27"
      WHEEL: rdflib
    - PYTHON: "C:\\Python27"
      WHEEL: url==0.1.6
    - PYTHON: "C:\\Python27"
      WHEEL: scandir
    - PYTHON: "C:\\Python27"
      WHEEL: pyyaml==3.12 
    - PYTHON: "C:\\Python27"
      WHEEL: pyyaml 
    - PYTHON: "C:\\Python27"
      WHEEL: cdifflib   
    - PYTHON: "C:\\Python27"
      WHEEL: edlib 
    - PYTHON: "C:\\Python27"
      WHEEL: hyperscan  
    - PYTHON: "C:\\Python27"
      WHEEL: pyroaring 

    - PYTHON: "C:\\Python27-x64"
      WHEEL: pyahocorasick
    - PYTHON: "C:\\Python27-x64"
      WHEEL: lxml
    - PYTHON: "C:\\Python27-x64"
      WHEEL: tinyarray
    - PYTHON: "C:\\Python27-x64"
      WHEEL: simplejson
    - PYTHON: "C:\\Python27-x64"
      WHEEL: billiard
    - PYTHON: "C:\\Python27-x64"
      WHEEL: psutil
    - PYTHON: "C:\\Python27-x64"
      WHEEL: intbitset
    - PYTHON: "C:\\Python27-x64"
      WHEEL: bitarray
    - PYTHON: "C:\\Python27-x64"
      WHEEL: pycryptodome
    - PYTHON: "C:\\Python27-x64"
      WHEEL: rdflib
    - PYTHON: "C:\\Python27-x64"
      WHEEL: url==0.1.6
    - PYTHON: "C:\\Python27-x64"
      WHEEL: scandir
    - PYTHON: "C:\\Python27-x64"
      WHEEL: pyyaml==3.12 
    - PYTHON: "C:\\Python27-x64"
      WHEEL: pyyaml 
    - PYTHON: "C:\\Python27-x64"
      WHEEL: cdifflib   
    - PYTHON: "C:\\Python27-x64"
      WHEEL: edlib 
    - PYTHON: "C:\\Python27-x64"
      WHEEL: hyperscan  
    - PYTHON: "C:\\Python27-x64"
      WHEEL: pyroaring 

    - PYTHON: "C:\\Python36"
      WHEEL: pyahocorasick
    - PYTHON: "C:\\Python36"
      WHEEL: lxml
    - PYTHON: "C:\\Python36"
      WHEEL: tinyarray
    - PYTHON: "C:\\Python36"
      WHEEL: simplejson
    - PYTHON: "C:\\Python36"
      WHEEL: billiard
    - PYTHON: "C:\\Python36"
      WHEEL: psutil
    - PYTHON: "C:\\Python36"
      WHEEL: intbitset
    - PYTHON: "C:\\Python36"
      WHEEL: bitarray
    - PYTHON: "C:\\Python36"
      WHEEL: pycryptodome
    - PYTHON: "C:\\Python36"
      WHEEL: rdflib
    - PYTHON: "C:\\Python36"
      WHEEL: url==0.1.6
    - PYTHON: "C:\\Python36"
      WHEEL: scandir
    - PYTHON: "C:\\Python36"
      WHEEL: pyyaml==3.12 
    - PYTHON: "C:\\Python36"
      WHEEL: pyyaml 
    - PYTHON: "C:\\Python36"
      WHEEL: cdifflib   
    - PYTHON: "C:\\Python36"
      WHEEL: edlib 
    - PYTHON: "C:\\Python36"
      WHEEL: hyperscan  
    - PYTHON: "C:\\Python36"
      WHEEL: pyroaring 

    - PYTHON: "C:\\Python36-x64"
      WHEEL: pyahocorasick
    - PYTHON: "C:\\Python36-x64"
      WHEEL: lxml
    - PYTHON: "C:\\Python36-x64"
      WHEEL: tinyarray
    - PYTHON: "C:\\Python36-x64"
      WHEEL: simplejson
    - PYTHON: "C:\\Python36-x64"
      WHEEL: billiard
    - PYTHON: "C:\\Python36-x64"
      WHEEL: psutil
    - PYTHON: "C:\\Python36-x64"
      WHEEL: intbitset
    - PYTHON: "C:\\Python36-x64"
      WHEEL: bitarray
    - PYTHON: "C:\\Python36-x64"
      WHEEL: pycryptodome
    - PYTHON: "C:\\Python36-x64"
      WHEEL: rdflib
    - PYTHON: "C:\\Python36-x64"
      WHEEL: url==0.1.6
    - PYTHON: "C:\\Python36-x64"
      WHEEL: scandir
    - PYTHON: "C:\\Python36-x64"
      WHEEL: pyyaml==3.12 
    - PYTHON: "C:\\Python36-x64"
      WHEEL: pyyaml 
    - PYTHON: "C:\\Python36-x64"
      WHEEL: cdifflib   
    - PYTHON: "C:\\Python36-x64"
      WHEEL: edlib 
    - PYTHON: "C:\\Python36-x64"
      WHEEL: hyperscan  
    - PYTHON: "C:\\Python36-x64"
      WHEEL: pyroaring 

#    - PYTHON: "C:\\Python27-x64"
#    - PYTHON: "C:\\Python36"
#    - PYTHON: "C:\\Python36-x64"


install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip wheel
  # Fix MSVC builds for 64-bit Python. See:
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"
  - mkdir wheelhouse

# use test step instead
build: false

test_script:
  - python -m pip wheel --wheel-dir=wheelhouse %WHEEL%
  - dir /S /B

artifacts:
  - path: wheelhouse\*

deploy:
  - provider: BinTray
    username: pombreda
    version: "1"
    override: true
    api_key:
      secure: vfOXPuSdGaUBQWCWhtXGWOKFoWulmg8dl3J8EP7RodmMN96VH8yeMQIHdU3f4+l/
    subject: pombreda
    repo: thirdparty2
    package: thirdparty2
    publish: true
