version: 1.0.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip wheel"

build: off

test_script:
  - mkdir wheels
  - cmd: "%PYTHON%\\python.exe -m pip wheel pyahocorasick --wheel-dir=wheels"
  - cmd: "%PYTHON%\\python.exe -m pip wheel intbitset --wheel-dir=wheels"
  - cmd: "%PYTHON%\\python.exe -m pip wheel bitarray --wheel-dir=wheels"
  - cmd: "%PYTHON%\\python.exe -m pip wheel lxml==3.6.0 --wheel-dir=wheels"
  - cmd: "%PYTHON%\\python.exe -m pip wheel tinyarray --wheel-dir=wheels"
  - dir
  - dir wheels

artifacts:
  - path: wheels\*

deploy:
  - provider: BinTray
    username: pombreda
    version: "1"
    api_key:
      secure: vfOXPuSdGaUBQWCWhtXGWOKFoWulmg8dl3J8EP7RodmMN96VH8yeMQIHdU3f4+l/
    subject: pombreda
    repo: thirdparty
    package: thirdparty
    publish: true
    override: true
