version: 1.0.{build}

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip wheel"

build: off

test_script:
  - mkdir wheels
  - cmd: "%PYTHON%\\python.exe -m pip install wheel"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels pyahocorasick"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels lxml"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels tinyarray"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels simplejson"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels billiard"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels psutil"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels intbitset"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels bitarray"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels pycryptodome"
  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels rdflib"
#  - cmd: "%PYTHON%\\python.exe -m pip wheel --wheel-dir=wheels url==0.1.6"
  - cmd: "%PYTHON%\\python.exe -m pip wheel scandir --wheel-dir=wheels"
  - cmd: "%PYTHON%\\python.exe -m pip wheel pyyaml==3.12 --wheel-dir=wheels"
  - cmd: "%PYTHON%\\python.exe -m pip wheel pyyaml --wheel-dir=wheels"
  
  - dir
  - dir wheels

artifacts:
  - path: wheels\*

deploy:
  - provider: BinTray
    username: pombreda
    version: "2"
    override: true
    api_key:
      secure: vfOXPuSdGaUBQWCWhtXGWOKFoWulmg8dl3J8EP7RodmMN96VH8yeMQIHdU3f4+l/
    subject: pombreda
    repo: thirdparty
    package: thirdparty
    publish: true
