environment:
  global:
    WHEELS: pyahocorasick
        lxml
        tinyarray
        simplejson
        billiard
        psutil
        intbitset
        bitarray
        pycryptodome
        rdflib
        url==0.1.6
        scandir
        pyyaml
        cdifflib
        edlib
        hyperscan
        pyroaring

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip wheel
  - mkdir wheelhouse

# use test step instead
build: false

test_script:
  - for %%I in (%WHEELS%) do python -m pip wheel --wheel-dir=wheelhouse %%I
  - dir /S /B

artifacts:
  - path: wheelhouse\*

deploy:
  - provider: BinTray
    username: pombreda
    version: "1"
    override: true
    api_key:
      secure: vfOXPuSdGaUBQWCWhtXGWOKFoWulmg8dl3J8EP7RodmMN96VH8yeMQIHdU3f4+l/
    subject: pombreda
    repo: thirdparty2
    package: thirdparty2
    publish: true
