environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - WHEEL: pyahocorasick
    - WHEEL: lxml
    - WHEEL: tinyarray
    - WHEEL: simplejson
    - WHEEL: billiard
    - WHEEL: psutil
    - WHEEL: intbitset
    - WHEEL: bitarray
    - WHEEL: pycryptodome
    - WHEEL: rdflib
    - WHEEL: url==0.1.6
    - WHEEL: scandir
    - WHEEL: pyyaml==3.12 
    - WHEEL: pyyaml 
    - WHEEL: cdifflib   
    - WHEEL: edlib 
    - WHEEL: hyperscan  
    - WHEEL: pyroaring 

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip wheel
  # Fix MSVC builds for 64-bit Python. See:
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"
  - mkdir wheelhouse

# use test step instead
build: false

test_script:
  - python -m pip wheel --wheel-dir=wheelhouse %WHEEL%
  - dir /S /B

artifacts:
  - path: wheelhouse\*

deploy:
  - provider: BinTray
    username: pombreda
    version: "1"
    override: true
    api_key:
      secure: vfOXPuSdGaUBQWCWhtXGWOKFoWulmg8dl3J8EP7RodmMN96VH8yeMQIHdU3f4+l/
    subject: pombreda
    repo: thirdparty2
    package: thirdparty2
    publish: true
